name: Update 
on:
  push:
    branches:
      - master
#  schedule:
#    - cron: "0 */8 * * *" # every 8 hour
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "? NOTE: The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "? NOTE: This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "? NOTE: The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "? NOTE: The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "? NOTE: The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "? NOTE: This job's status is ${{ job.status }}."
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "? NOTE: The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "? NOTE: The workflow is now ready to test your code on the runner."

      - name: Regression test
        run: |
          sh test.sh
      - run: echo "? NOTE: This job's status is ${{ job.status }}."
